#################################################################
#                                                               #
#                     Packages/Garage Door                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    sensor.garage_door_status:
      friendly_name: Garage Door
      icon: mdi:garage
      
#################################################################
#                                                               #
#                           Groups                              #
#                                                               #
#################################################################

group:
  garage:
    name: Garage
    view: no
    entities:
      - sensor.garage_door_status
      - sensor.garage

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor: 

####################################################
#                                                  #
#                  Sensors - MQTT                  #
#                                                  #
####################################################

  - platform: mqtt
    name: "Garage Door Status"
    state_topic: "garagedoor"

####################################################
#                                                  #
#                Sensors - Template                #
#                                                  #
####################################################
    
  - platform: template
    sensors:
      garage_door:
        friendly_name: "Garage Door"
        value_template: >-
          {% if is_state('sensor.garage_door_status', 'Open') %}
            Open
          {% elif is_state('sensor.garage_door_status', 'Closed') %}
            Closed
          {% else %}
            Obstruction
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.garage_door_status', 'Open') %}
            mdi:garage-open
          {% elif is_state('sensor.garage_door_status', 'Closed') %}
            mdi:garage
          {% else %}
            mdi:garage-alert
          {% endif %}

####################################################
#                                                  #
#                  Binary Sensors                  #
#                                                  #
####################################################
          
binary_sensor:
  - platform: template
    sensors:
## Door Sensors
      garage:
        friendly_name: Garage
        device_class: door
        entity_id: sensor.garage_door
        value_template: "{{ is_state('sensor.garage_door', 'Open') }}"
        icon_template: >-
          {% if is_state('sensor.garage_door', 'Open') %}
            mdi:garage-open
          {% elif is_state('sensor.garage_door', 'Obstruction') %}
            mdi:garage-alert     
          {% elif is_state('sensor.garage_door', 'Closed') %}
            mdi:garage     
          {% else %}
            mdi:alert
          {% endif %}
    
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################


## All automations for this package have now been moved to Node-RED please see Node-Red Flows folder within this package for more infomation! ##
 
automation:
